# SPDX-License-Identifier: MPL-2.0
# The former "Integration tests" job here was a structural no-op: it ran
# `cargo test` in a repo with no Cargo.toml and looped over
# tests/integration/*.sh which never existed — always green, gating nothing.
# Real integration coverage now lives in idris2.yml (Idris suites + the
# Idris->Zig FFI runtime test) and zig-ffi.yml (C-ABI link + Zig tests).
name: E2E and Integration Tests
on:
  push: {branches: [main]}
  pull_request: {branches: ['**']}
permissions:
  contents: read
jobs:
  e2e:
    name: E2E tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Run E2E tests
        run: bash tests/e2e_test.sh
